# Generated by Django 2.1.3 on 2018-12-07 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='priority',
            field=models.CharField(choices=[('P1', 'P1'), ('P2', 'P2'), ('P3', 'P3'), ('P4', 'P4'), ('P5', 'P5')], default='P5', max_length=2),
        ),
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.IntegerField(choices=[('PROBLEM', 'Problem'), ('INCIDENT', 'Incident')]),
        ),
        migrations.AlterField(
            model_name='event',
            name='type',
            field=models.CharField(max_length=10, verbose_name=(('PROBLEM', 'Problem'), ('INCIDENT', 'Incident'))),
        ),
    ]
