# Generated by Django 2.1.3 on 2018-12-07 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_auto_20181207_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.IntegerField(choices=[('1', '1'), ('2', '2'), ('3', '3')]),
        ),
    ]
