# Generated by Django 2.1.3 on 2018-12-07 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_auto_20181207_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='type',
            field=models.CharField(choices=[('PROBLEM', 'Problem'), ('INCIDENT', 'Incident')], max_length=10),
        ),
    ]
