# Generated by Django 2.1.3 on 2018-12-07 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_auto_20181207_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.IntegerField(choices=[('1', '1'), ('2', '2'), ('3', '3')], default='1'),
        ),
        migrations.AlterField(
            model_name='event',
            name='type',
            field=models.CharField(choices=[('PROBLEM', 'Problem'), ('INCIDENT', 'Incident')], default='Problem', max_length=10),
        ),
    ]
