# Generated by Django 2.2.1 on 2019-05-18 17:56

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NegScores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precision', models.DecimalField(decimal_places=3, max_digits=5)),
                ('recall', models.DecimalField(decimal_places=3, max_digits=5)),
                ('f1', models.DecimalField(decimal_places=3, max_digits=5)),
                ('support', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PosScores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precision', models.DecimalField(decimal_places=3, max_digits=5)),
                ('recall', models.DecimalField(decimal_places=3, max_digits=5)),
                ('f1', models.DecimalField(decimal_places=3, max_digits=5)),
                ('support', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=70)),
                ('contactNo', models.BigIntegerField()),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('reason', models.CharField(choices=[('REQUEST ACCESS', 'REQUEST ACCESS'), ('CHANGE OF PRIVILEGE', 'CHANGE OF PRIVILEGE'), ('CONTACT', 'CONTACT')], default='REQUEST ACCESS', max_length=20)),
                ('other', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='WeightedAvg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precision', models.DecimalField(decimal_places=3, max_digits=5)),
                ('recall', models.DecimalField(decimal_places=3, max_digits=5)),
                ('f1', models.DecimalField(decimal_places=3, max_digits=5)),
                ('support', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewText', models.TextField()),
                ('predictSentiment', models.CharField(choices=[('POSITIVE', 'positive'), ('NEGATIVE', 'negative')], max_length=10)),
                ('actualSentiment', models.CharField(choices=[('POSITIVE', 'positive'), ('NEGATIVE', 'negative')], max_length=10)),
                ('batch_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('avg_batch_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.WeightedAvg')),
                ('neg_batch_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.NegScores')),
                ('pos_batch_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.PosScores')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('PROBLEM', 'Problem'), ('INCIDENT', 'Incident')], default='Problem', max_length=10)),
                ('reference', models.CharField(max_length=10)),
                ('status', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3')], default='1')),
                ('resolution_date', models.DateTimeField()),
                ('priority', models.CharField(choices=[('P1', 'P1'), ('P2', 'P2'), ('P3', 'P3'), ('P4', 'P4'), ('P5', 'P5')], default='P5', max_length=2)),
                ('assigned_team', models.CharField(choices=[('NISPI/DWP', 'NISPI/DWP')], default='NISPI/DWP', max_length=20)),
                ('summary', models.TextField()),
                ('assigned_person', models.ForeignKey(default=django.contrib.auth.models.User, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
