# Generated by Django 2.2.1 on 2019-05-18 20:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='batch_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
