# Generated by Django 2.2.1 on 2019-05-18 21:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_auto_20190518_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='batch_date',
            field=models.DateTimeField(default=datetime.date.today),
        ),
    ]
