# Generated by Django 2.2.1 on 2019-05-18 21:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_auto_20190518_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='batch_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
