# Generated by Django 2.2.1 on 2019-05-22 16:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_auto_20190518_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='batch_date',
            field=models.DateTimeField(default=datetime.date(2019, 5, 22)),
        ),
        migrations.DeleteModel(
            name='Event',
        ),
    ]
